name: Price Update Bot

on:
  schedule:
    - cron: "0,10,20,30,40,50 * * * *"   # Only at 00,10,20,30,40,50
  workflow_dispatch:


permissions:
  contents: write


jobs:
  update:
    runs-on: ubuntu-latest


    steps:

      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v4


      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"


      # Install dependencies
      - name: Install Requests
        run: pip install requests


      # Wait 30 seconds (to reach :30)
      - name: Wait 30 Seconds
        run: sleep 30


      # Run update script
      - name: Run Price Script
        run: python update_rates.py


      - name: Commit and Push
  run: |
    git config user.name "Auto Bot"
    git config user.email "bot@users.noreply.github.com"

    git pull origin main --rebase

    date > heartbeat.txt

    git add index.html heartbeat.txt
    git commit -m "Auto update prices" || exit 0

    git push origin main
