name: Price Update Bot

on:
  schedule:
    - cron: "*/10 * * * *"   # Every 10 minutes
  workflow_dispatch:


jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write


    steps:

      # Get repo files
      - name: Checkout Repository
        uses: actions/checkout@v4


      # Install Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"


      # Install dependencies
      - name: Install Requests
        run: pip install requests


      # Wait for exact :30 second timing
      - name: Wait 30 Seconds
        run: sleep 30


      # Run updater
      - name: Run Price Script
        run: python update_rates.py


      # Commit updated HTML
      - name: Commit and Push
        run: |
          git config user.name "Auto Bot"
          git config user.email "bot@users.noreply.github.com"

          git add index.html
          git commit -m "Auto update prices" || exit 0
          git push
