name: Price Update Bot

on:
  schedule:
    - cron: "*/10 * * * *"   # Every 10 minutes (SAFE)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Requests
        run: pip install requests

      - name: Run Script
        run: python update_rates.py

      - name: Commit & Push
        run: |
          git config user.name "Auto Bot"
          git config user.email "bot@users.noreply.github.com"

          git add index.html
          git commit -m "Auto update prices" || exit 0
          git push
